### ISSUE TITLE
Add node_modules to .gitignore + remove from repo?

### ISSUE THREAD

**Issue by bearcanrun** [AAMasters/AAMariam-Trading-Bot#3]
_node_modules_ folder isn't usually checked in with .git repos as any required installable dependencies should be listed in package.json. Currently, it bloats the repo by ~12mb. 

I didn't see any required dependencies in the bot code. The package.json also looks like it needs to be updated too.

**Comment by Luis-Fernando-Molina** [comment]
Done, not only at this repo but all the others.
